"""empty message

Revision ID: 725effea59ae
Revises: 10b9f17adb29
Create Date: 2021-03-25 09:46:10.683961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725effea59ae'
down_revision = '10b9f17adb29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('in_stock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'in_stock')
    # ### end Alembic commands ###
